window.PROPERTYSETU_LOCATIONS = [
  'Hiran Magri Sector 1',
  'Hiran Magri Sector 2',
  'Hiran Magri Sector 3',
  'Hiran Magri Sector 4',
  'Hiran Magri Sector 5',
  'Hiran Magri Sector 6',
  'Hiran Magri Sector 7',
  'Hiran Magri Sector 8',
  'Hiran Magri Sector 9',
  'Hiran Magri Sector 11',
  'Pratap Nagar',
  'Pratap Nagar Extension',
  'New Bhupalpura',
  'Old Bhupalpura',
  'Ashok Nagar',
  'Shastri Circle',
  'Ambamata',
  'Saheli Nagar',
  'Chetak Circle',
  'Fatehpura',
  'Sukher',
  'Bhuwana',
  'Bedla',
  'Shobhagpura',
  'Madhuban',
  'University Road',
  'Rani Road',
  'Pichola',
  'Goverdhan Vilas',
  'Balicha',
  'Debari',
  'Savina',
  'Titardi',
  'Udiapole',
  'Delhi Gate',
  'Surajpole',
  'Hathipole',
  'Bapu Bazar',
  'Dhanmandi',
  'Badi',
  'Badi Lake Road',
  'Bohra Ganesh Ji',
  'Umarda',
  'Sisarma',
  'Eklingpura',
  'Kaladwas',
  'Airport Road',
  'Mavli',
  'Dabok',
  'Gogunda',
  'Nai',
  'Madri Industrial Area',
  'Transport Nagar',
  'Sector 14',
  'Sector 13',
  'Roop Sagar Road',
  '100 Feet Road',
  'Ayad',
  'Neemach Mata',
  'Chitrakoot Nagar',
  'Mahaveer Colony Park Area',
];
