window.PROPERTYSETU_LOCATIONS = [
  'Hiran Magri Sector 1',
  'Hiran Magri Sector 2',
  'Hiran Magri Sector 3',
  'Hiran Magri Sector 4',
  'Hiran Magri Sector 5',
  'Hiran Magri Sector 6',
  'Hiran Magri Sector 7',
  'Hiran Magri Sector 8',
  'Hiran Magri Sector 9',
  'Hiran Magri Sector 10',
  'Hiran Magri Sector 11',
  'Hiran Magri Sector 13',
  'Hiran Magri Sector 14',
  'Pratap Nagar',
  'Pratap Nagar Chouraha',
  'Pratap Nagar Extension',
  'Sukher',
  'Sukher Industrial Area',
  'Bhuwana',
  'Bhuwana Bypass',
  'Bedla',
  'Fatehpura',
  'Shobhagpura',
  'Saheli Nagar',
  'Chetak Circle',
  'Ashok Nagar',
  'Bhopalpura',
  'University Road',
  'Madhuban',
  'Rani Road',
  'Ambamata',
  'Panchwati',
  'New Fatehpura',
  'Sector 14 Govardhan Vilas',
  'Goverdhan Vilas',
  'Savina',
  'Savina Kheda',
  'Savina Main Road',
  'Titardi',
  'Debari',
  'Debari Madri',
  'Balicha',
  'Balicha Bypass',
  'Umarda',
  'Umarda Road',
  'Airport Road',
  'Maharana Pratap Airport Area',
  'Badi',
  'Badi Lake Road',
  'Pichola',
  'Gangaur Ghat',
  'Doodh Talai',
  'Jagatpura Udaipur',
  'Purohito Ki Madri',
  'Ayad',
  'Durga Nursery Road',
  'Court Chouraha',
  'Surajpole',
  'Delhi Gate',
  'Udiapole',
  'Shastri Circle',
  'Chetak Marg',
  'Hathipole',
  'Brahmpole',
  'Chandpole',
  'Kumharon Ka Bhatta',
  'Tekri',
  'Malla Talai',
  'Neemach Mata Road',
  'Sec 3 Hiran Magri',
  'Sec 4 Hiran Magri',
  'Sec 5 Hiran Magri',
  'Sec 6 Hiran Magri',
  'Sec 7 Hiran Magri',
  'Sec 8 Hiran Magri',
  'Sec 9 Hiran Magri',
  'Sec 11 Hiran Magri',
  'Sec 14 Hiran Magri',
  'Gariyawas',
  'Manwakheda',
  'Mavli',
  'Mavli Junction',
  'Dabok',
  'Dabok Chouraha',
  'Kanpur Udaipur',
  'Badi Badgaon',
  'Badgaon',
  'Sisarma',
  'Nai',
  'Naiyon Ki Talai',
  'Bedwas',
  'Bhinder',
  'Vallabhnagar',
  'Bichhiwara Road',
  'Eklingpura',
  'Madri',
  'Madri Industrial Area',
  'Kaladwas',
  'Kaladwas Industrial Area',
  'Sukher Chouraha',
  'Badi Road',
  'Fateh Sagar Road',
  'Moti Magri',
  'Ravji Ka Hata',
  'Zinc Smelter Area',
  'Zawar Mines',
  'Jhadol',
  'Gogunda',
  'Sayra',
  'Kherwara',
  'Rishabhdeo',
  'Salumber',
  'Lasadia',
  'Kotra',
  'Sarada',
  'Mavli Rural',
  'Badgaon Rural',
  'Girwa',
  'Girwa Rural',
  'Bhatewar',
  'Kurabad',
  'Nandeshwar',
  'Bansda',
  'Kanod',
  'Semari',
  'Jaisamand Road',
  'Fatehnagar',
  'Rupnagar',
  'Sewashram',
  'HMT Colony',
  'Adarsh Nagar',
  'Transport Nagar',
  'Pahada',
  'Pula',
  'Navratan Complex Area',
  '100 Feet Road Udaipur'
];
