window.PROPERTYSETU_LOCATIONS = [
  'Hiran Magri Sector 1',
  'Hiran Magri Sector 2',
  'Hiran Magri Sector 3',
  'Pratap Nagar',
  'Ambamata',
  'Sukher',
  'Bhuwana',
  'Bedla',
  'Fatehpura',
  'Saheli Nagar',
  'Shobhagpura',
  'Madhuban',
  'University Road',
  'Rani Road',
  'Pichola',
  'Goverdhan Vilas',
  'Balicha',
  'Debari',
  'Savina',
  'Titardi',
  'Udiapole',
  'Delhi Gate',
  'Surajpole',
  'Hathipole',
  'Bapu Bazar',
  'Dhanmandi',
  'Badi',
  'Badi Lake Road',
  'Bohra Ganesh Ji',
  'Umarda',
  'Sisarma',
  'Eklingpura',
  'Airport Road',
  'Mavli',
  'Dabok',
  'Gogunda',
  'Nai',
  'Madri Industrial Area',
  'Transport Nagar',
  '100 Feet Road',
  'Ayad',
  'Neemach Mata',
  'Chitrakoot Nagar',
];
